# Make the OSX pasteboard work
set -g default-command "reattach-to-user-namespace -l zsh"


# remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Make new window start in pwd of current window
bind c new-window -c "#{pane_current_path}"

# split panes using | and -
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

#quick reload config file
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

# resize panes
bind -n M-Down resize-pane -D
bind -n M-Up resize-pane -U
bind -n M-Left resize-pane -L
bind -n M-Right resize-pane -R

# don't rename windows automatically
set-option -g allow-rename off
